export const MOVIES_SEARCH_BEGIN = 'MOVIES_SEARCH_BEGIN';
export const MOVIES_SEARCH_SUCCESS = 'MOVIES_SEARCH_SUCCESS';
export const MOVIES_SEARCH_FAILURE = 'MOVIES_SEARCH_FAILURE';
export const MOVIES_SEARCH_DISMISS_ERROR = 'MOVIES_SEARCH_DISMISS_ERROR';
