export const GISTS_SEARCH_BEGIN = 'GISTS_SEARCH_BEGIN';
export const GISTS_SEARCH_SUCCESS = 'GISTS_SEARCH_SUCCESS';
export const GISTS_SEARCH_FAILURE = 'GISTS_SEARCH_FAILURE';
export const GISTS_SEARCH_DISMISS_ERROR = 'GISTS_SEARCH_DISMISS_ERROR';
export const GISTS_FETCH_GIST_LIST_BEGIN = 'GISTS_FETCH_GIST_LIST_BEGIN';
export const GISTS_FETCH_GIST_LIST_SUCCESS = 'GISTS_FETCH_GIST_LIST_SUCCESS';
export const GISTS_FETCH_GIST_LIST_FAILURE = 'GISTS_FETCH_GIST_LIST_FAILURE';
export const GISTS_FETCH_GIST_LIST_DISMISS_ERROR = 'GISTS_FETCH_GIST_LIST_DISMISS_ERROR';
